### ISSUE TITLE
Walking Distance

### ISSUE THREAD

**Issue by lwaters5** [microapps/store-locator#1]
Can this store-locator calculate the distance using walking distance? If so, how would I change the code to do this? Thank you.

**Comment by jimmyn** [comment]
It calculates distance using [computeDistanceBetween](https://developers.google.com/maps/documentation/javascript/reference/geometry#spherical.computeDistanceBetween) google maps api method. It is a direct distance betwean 2 points, not even a driving distance. You can make a fork and customize [this method](https://github.com/microapps/store-locator/blob/master/src/components/StoreLocator.js#L56) if you like.
